services:
  postgres:
    image: 'postgres:18-alpine'
    restart: always
    environment:
      - 'POSTGRES_DB=springVueDB'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - '15432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    image: 'spring-boot-vue-crud' # Replace with your Docker image name
    build: spring-boot-vue-crud
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/springVueDB'
      SPRING_DATASOURCE_USERNAME: 'postgres'
      SPRING_DATASOURCE_PASSWORD: 'password'
      SPRING_PROFILES_ACTIVE: docker

volumes:
  db-data: